[package]
name = "donut"
version = "0.1.0"
authors = ["Arnaud <arnaud.golfouse@free.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
